/**
 * Main export for shared types
 * Explicitly re-export to avoid duplicate type conflicts
 */

// Common types (base types used across all domains)
export type * from './common';

// Auth types
export type * from './auth';

// Customer domain types
export type {
  Customer,
  CustomerSummary,
  CustomerProfile as CustomerProfileFromCustomer,
  LinkedProduct,
  ProductType,
  CustomerSearchRequest,
  CustomerSearchResponse,
  CreateCustomerRequest,
  UpdateCustomerRequest,
  CustomerDocument,
  CustomerPreference,
  CommunicationPreference,
  TransactionAlertPreference,
  TransactionAlertType,
  MarketingPreference,
  SecurityPreference,
  MfaMethod as CustomerMfaMethod,
  TrustedDevice,
  CustomerSession,
  DeviceInfo as CustomerDeviceInfo,
  GeoLocation as CustomerGeoLocation,
  CustomerActivity,
  CustomerActivityType,
} from './customer';

// Card domain types
export type {
  Card,
  CardSummary,
  CardControls,
  CardUsage,
  CardSearchRequest,
  CardSearchResponse,
  CreateCardRequest,
  UpdateCardRequest,
  CardControlUpdateRequest,
  CardActionRequest,
  CardAction,
  CardReissueRequest,
  CardReplaceRequest,
  CardLimitEnhancementRequest,
  CardLimitEnhancementResponse,
  DocumentReference,
  RequestStatus as CardRequestStatus,
  CardStatement,
  CardStatementTransaction,
  CardTransaction,
  TransactionStatus as CardTransactionStatus,
  TransactionType as CardTransactionType,
  InstallmentInfo as CardInstallmentInfo,
  CardReward,
  ExpiringPoints as CardExpiringPoints,
  EarningRate,
  RewardRedemption as CardRewardRedemption,
  VelocityCheck,
  DeviceInfo as CardDeviceInfo,
  GeoLocation as CardGeoLocation,
  Address as CardAddress,
} from './card';

// Transaction domain types
export type {
  Transaction,
  TransactionSummary,
  TransactionSearchRequest,
  TransactionSearchResponse,
  TransactionStats,
  TransactionCategory,
  TransactionStatus,
  TransactionType,
  InstallmentInfo as TransactionInstallmentInfo,
  DisputeStatus,
  TransactionRule,
  TransactionRuleCondition,
  TransactionRuleField,
  TransactionRuleOperator,
  TransactionRuleAction,
  TransactionRuleActionType,
  RecurringTransaction,
  RecurrenceFrequency,
  TransactionExportRequest,
  TransactionExportResponse,
  CategoryStat,
  ChannelStat,
  StatusStat,
  TypeStat,
  MonthlyStat,
} from './transaction';

// Payment domain types
export type {
  Payment,
  PaymentSummary,
  PaymentSearchRequest,
  PaymentSearchResponse,
  CreatePaymentRequest,
  RecurringPaymentConfig,
  RecurrenceFrequency as PaymentRecurrenceFrequency,
  PaymentResponse,
  MfaChallenge,
  MfaMethod as PaymentMfaMethod,
  MfaVerificationRequest,
  MfaVerificationResponse,
  Beneficiary,
  BeneficiaryType,
  AddBeneficiaryRequest,
  BeneficiaryVerificationRequest,
  BeneficiaryVerificationResponse,
  PaymentLimits,
  PaymentSchedule,
  PaymentAnalytics,
  MethodStat,
  PurposeStat,
  StatusStat as PaymentStatusStat,
  ChannelStat as PaymentChannelStat,
  MonthlyStat as PaymentMonthlyStat,
  PaymentDispute,
  DisputeReason,
  DisputeStatus as PaymentDisputeStatus,
  DisputeResolution,
  DeviceInfo as PaymentDeviceInfo,
  GeoLocation as PaymentGeoLocation,
  AccountType,
  PaymentMethod,
  PaymentMode,
  PaymentPurpose,
  PaymentStatus,
} from './payment';

// Reward domain types
export type {
  RewardAccount,
  RewardTier,
  ExpiringPoints as RewardExpiringPoints,
  RewardTransaction,
  RewardTransactionType,
  RewardTransactionStatus,
  RewardSource,
  RewardTransactionSummary,
  RewardTransactionSearchRequest,
  RewardTransactionSearchResponse,
  RewardCatalogItem,
  RewardCategory,
  RewardCatalogType,
  RewardRedemption,
  RedemptionStatus as RewardRedemptionStatus,
  DeliveryDetails,
  VoucherDetails,
  StatementCreditDetails,
  Address as RewardAddress,
  RedemptionRequest,
  RedemptionResponse,
  RewardEarningRule,
  TransactionCategory as RewardTransactionCategory,
  RewardSummary,
  CategoryEarning,
  RewardAnalytics,
  TierStat,
  CategoryStat as RewardCategoryStat,
  MonthlyStat as RewardMonthlyStat,
} from './reward';

// EMI domain types
export type {
  EmiPlan,
  EmiPlanStatus,
  EmiPlanSummary,
  EmiPlanSearchRequest,
  EmiPlanSearchResponse,
  EmiEligibilityRequest,
  EmiEligibilityResponse,
  EligibleTenure,
  EmiBookingRequest,
  EmiBookingResponse,
  EmiPreclosureRequest,
  EmiPreclosureResponse,
  EmiInstallment,
  InstallmentStatus,
  EmiConfiguration,
  TenureInterestRate,
  EmiSimulationRequest,
  EmiSimulationResponse,
  AmortizationEntry,
  EmiAnalytics,
  TenureStat,
  StatusStat as EmiStatusStat,
  MonthlyStat as EmiMonthlyStat,
  DeviceInfo as EmiDeviceInfo,
  GeoLocation as EmiGeoLocation,
} from './emi';

// Loan domain types
export type {
  LoanOffer,
  LoanType,
  LoanFeature,
  LoanApplication,
  LoanPurpose,
  EmploymentDetails,
  IncomeDetails,
  OtherIncomeSource,
  ExistingLoan as LoanExistingLoan,
  PropertyDetails,
  VehicleDetails,
  EducationDetails,
  GoldDetails,
  LoanApplicationStatus,
  DisbursementMode,
  LoanDocument,
  DocumentType as LoanDocumentType,
  DocumentReference as LoanDocumentReference,
  Address as LoanAddress,
  LoanAccount,
  LoanAccountStatus,
  LoanAccountSummary,
  LoanAccountSearchRequest,
  LoanAccountSearchResponse,
  LoanEmi,
  EmiStatus as LoanEmiStatus,
  LoanPreclosureRequest,
  LoanPreclosureResponse,
  LoanPartPrepaymentRequest,
  LoanPartPrepaymentResponse,
  LoanEligibilityRequest,
  LoanEligibilityResponse,
  EligibleLoanTenure,
  LoanSimulationRequest,
  LoanSimulationResponse,
  LoanAmortizationEntry,
  LoanAnalytics,
  TypeStat as LoanTypeStat,
  ApplicationStatusStat,
  MonthlyStat as LoanMonthlyStat,
  DeviceInfo as LoanDeviceInfo,
  GeoLocation as LoanGeoLocation,
} from './loan';

// FASTag domain types
export type {
  FastagAccount,
  VehicleClass,
  VehicleType,
  FastagStatus,
  KycStatus as FastagKycStatus,
  FastagAccountSummary,
  FastagSearchRequest,
  FastagSearchResponse,
  CreateFastagRequest,
  VehicleDetails as FastagVehicleDetails,
  OwnerDetails,
  Address as FastagAddress,
  FastagRechargeRequest,
  FastagPaymentMethod,
  FastagRechargeResponse,
  RechargeStatus,
  FastagTransaction,
  FastagTransactionType,
  FastagTransactionStatus,
  PlazaLocation,
  FastagTransactionSummary,
  FastagTransactionSearchRequest,
  FastagTransactionSearchResponse,
  FastagStatement,
  FastagReplacementRequest,
  FastagReplacementResponse,
  ReplacementStatus,
  FastagAnalytics,
  VehicleClassStat,
  StateStat,
  MonthlyStat as FastagMonthlyStat,
  DeviceInfo as FastagDeviceInfo,
  GeoLocation as FastagGeoLocation,
} from './fastag';

// Offer domain types
export type {
  Offer,
  OfferCategory,
  OfferType,
  OfferImage,
  OfferEligibility,
  EligibilityRule,
  OfferReward,
  OfferValidity,
  OfferRedemption,
  RedemptionMode,
  RedemptionStep,
  OfferLimits,
  OfferTargeting,
  GeographyTarget,
  OfferSummary,
  OfferSearchRequest,
  OfferSearchResponse,
  CustomerOffer,
  CustomerOfferStatus,
  CustomerOfferSearchRequest,
  CustomerOfferSearchResponse,
  ClaimOfferRequest,
  ClaimOfferResponse,
  RedeemOfferRequest,
  RedeemOfferResponse,
  RedemptionStatus as OfferRedemptionStatus,
  OfferAnalytics,
  CategoryStat as OfferCategoryStat,
  TypeStat as OfferTypeStat,
  StatusStat as OfferStatusStat,
  MonthlyStat as OfferMonthlyStat,
  SegmentStat,
  DeviceInfo as OfferDeviceInfo,
  GeoLocation as OfferGeoLocation,
} from './offer';

// Notification domain types
export type {
  Notification,
  NotificationType,
  NotificationCategory,
  NotificationPriority,
  NotificationStatus,
  NotificationRichContent,
  NotificationActionButton,
  NotificationCarouselItem,
  NotificationRecipient,
  ChannelPreference,
  NotificationSummary,
  NotificationSearchRequest,
  NotificationSearchResponse,
  NotificationTemplate,
  TemplateVariable,
  CreateNotificationRequest,
  BulkNotificationRequest,
  BulkNotificationResponse,
  BulkNotificationItem,
  NotificationPreference,
  ChannelNotificationPreference,
  CategoryChannelPreference,
  NotificationAnalytics,
  ChannelStat as NotificationChannelStat,
  TypeStat as NotificationTypeStat,
  CategoryStat as NotificationCategoryStat,
  PriorityStat,
  MonthlyStat as NotificationMonthlyStat,
} from './notification';

// Profile domain types
export type {
  CustomerProfile,
  PersonalInfo,
  ContactInfo,
  AddressInfo,
  Address,
  EmploymentInfo,
  FinancialInfo,
  ExistingLoan as ProfileExistingLoan,
  Investment,
  InsurancePolicy,
  Nominee,
  TaxResidency,
  FatcaCrsDeclaration,
  KycInfo,
  KycStatus,
  KycDocument,
  KycDocumentType,
  ProfilePreferences,
  NotificationPreferences,
  PrivacyPreferences,
  SecurityPreferences,
  AccessibilityPreferences,
  ProfileDocument,
  ProfileDocumentType,
  ProfileUpdateRequest,
  ProfileUpdateResponse,
  PendingVerification,
  AddressChangeRequest,
  AddressChangeResponse,
  ProfileAnalytics,
  EmploymentStat,
  AgeGroupStat,
  CityStat,
  StateStat as ProfileStateStat,
  KycStatusStat,
  RiskCategoryStat,
  DeviceInfo as ProfileDeviceInfo,
  GeoLocation as ProfileGeoLocation,
} from './profile';

// Admin domain types
export type {
  AdminUser,
  AdminUserStatus,
  AdminRole,
  AdminPermission,
  PermissionAction,
  PermissionScope,
  PermissionCondition,
  PermissionCategory,
  AdminMfaMethod,
  AdminUserSearchRequest,
  AdminUserSearchResponse,
  AdminRoleSearchRequest,
  AdminRoleSearchResponse,
  AdminPermissionSearchRequest,
  AdminPermissionSearchResponse,
  CreateAdminUserRequest,
  UpdateAdminUserRequest,
  AssignRoleRequest,
  RevokeRoleRequest,
  ResetMfaRequest,
  AdminAuditLog,
  AuditAction,
  AdminAuditSearchRequest,
  AdminAuditSearchResponse,
  AdminDashboardStats,
  SystemHealthSummary,
  ServiceHealth,
  DatabaseHealth,
  QueueHealth,
  CacheHealth,
  AdminAlert,
  AdminAnalytics,
  UserActivityStat,
  RoleDistributionStat,
  PermissionUsageStat,
  AuditSummaryStat,
  LoginStat,
  ActionStat,
} from './admin';

// Events
export type * from './events';
