apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  namespace: banking360
  labels:
    app: ledger-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      serviceAccountName: banking360-sa
      containers:
        - name: ledger-service
          image: banking360/ledger-service:latest
          ports:
            - containerPort: 8087
          env:
            - name: SERVER_PORT
              value: "8087"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: banking360
spec:
  selector:
    app: ledger-service
  ports:
    - port: 8087
      targetPort: 8087
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ledger-service-hpa
  namespace: banking360
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ledger-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ledger-service-pdb
  namespace: banking360
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ledger-service
