apiVersion: v1
kind: Secret
metadata:
  name: banking360-secrets
  namespace: banking360
type: Opaque
stringData:
  DB_USERNAME: "banking360"
  DB_PASSWORD: "banking360"
  JWT_SECRET: "dev-only-insecure-change-me"
